### PR TITLE
Benatti-Casaburo-Dei Vecchi-Fava-Trad

### PR DESCRIPTION
**Pull request by sarah-casaburo95**
[Benatti-Casaburo-Dei Vecchi-Fava-Trad.pdf](https://github.com/bnajafi/BuildingSimulationProject_Polimi_TES/files/1642549/Benatti-Casaburo-Dei.Vecchi-Fava-Trad.pdf)

### CODE REVIEW

**Comment by bnajafi** [comment]
Please read the guidelines and update your submission,

**Comment by sarah-casaburo95** [comment]
Goodmorning,
We read all the guidelines and we should have uploaded the file. How can we be sure?
Thank you
Sarah Casaburo

**Comment by bnajafi** [comment]
Good morning,
As indicated in the guidelines, you should put all the files (including the .pdf report and openStudio files) in a folder which is called with your surnames. Though in the submission I have just received the pdf file.

**Comment by sarah-casaburo95** [comment]
Thank you, I will upload it again.

**Comment by sarah-casaburo95** [comment]
We tried to upload again the files but we are not sure if they are there.

**Pull request merged**
